harbourmaster.settings:
  type: config_object
  label: Harbourmaster Configuration
  mapping:
    sso_cookie_domain:
      type: string
      label: SSO cookie domain
    sso_cookie_name:
      type: string
      label: SSO cookie name
    harbourmaster_lookup_ttl:
      type: integer
      label: HMS lookup TTL
    harbourmaster_api_url:
      type: uri
      label: HMS URL
    harbourmaster_api_tenant:
      type: string
      label: HMS Tenant
    user_manager_url:
      type: uri
      label: User manager URL
    harbourmaster_api_version:
      type: string
      label: API Version
