hms.settings:
  type: config_object
  label: Harbourmaster Configuration
  mapping:
    hms_api_url:
      type: uri
      label: HMS URL
    hms_api_tenant:
      type: string
      label: HMS Tenant
    token_ttl:
      type: integer
      label: Token TTL
    token_name:
      type: string
      label: Token Cookie Name
    user_manager_url:
      type: uri
      label: User manager URL